// <auto-generated />
using System;
using Billiard.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Billiard.DAL.Migrations
{
    [DbContext(typeof(BilliardDbContext))]
    [Migration("20251117070949_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Billiard.DAL.Entities.BanBium", b =>
                {
                    b.Property<int>("MaBan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_ban");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBan"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ghi_chu");

                    b.Property<DateTime?>("GioBatDau")
                        .HasColumnType("datetime")
                        .HasColumnName("gio_bat_dau");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("hinh_anh");

                    b.Property<int?>("MaKh")
                        .HasColumnType("int")
                        .HasColumnName("ma_kh");

                    b.Property<int>("MaKhuVuc")
                        .HasColumnType("int")
                        .HasColumnName("ma_khu_vuc");

                    b.Property<int>("MaLoai")
                        .HasColumnType("int")
                        .HasColumnName("ma_loai");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_tao")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("TenBan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ten_ban");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Trống")
                        .HasColumnName("trang_thai");

                    b.Property<int?>("ViTriX")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("vi_tri_x");

                    b.Property<int?>("ViTriY")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("vi_tri_y");

                    b.HasKey("MaBan")
                        .HasName("PK__ban_bia__03FFDF0D93987EF7");

                    b.HasIndex("MaKh");

                    b.HasIndex("MaKhuVuc");

                    b.HasIndex("MaLoai");

                    b.HasIndex(new[] { "TenBan" }, "UQ__ban_bia__5B4758ACF530C070")
                        .IsUnique();

                    b.ToTable("ban_bia", (string)null);
                });

            modelBuilder.Entity("Billiard.DAL.Entities.BangLuong", b =>
                {
                    b.Property<int>("MaLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_luong");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLuong"));

                    b.Property<decimal?>("LuongCoBan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12, 0)")
                        .HasDefaultValue(0m)
                        .HasColumnName("luong_co_ban");

                    b.Property<int>("MaNv")
                        .HasColumnType("int")
                        .HasColumnName("ma_nv");

                    b.Property<int>("Nam")
                        .HasColumnType("int")
                        .HasColumnName("nam");

                    b.Property<DateTime?>("NgayTinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_tinh")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("Phat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12, 0)")
                        .HasDefaultValue(0m)
                        .HasColumnName("phat");

                    b.Property<decimal?>("PhuCap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12, 0)")
                        .HasDefaultValue(0m)
                        .HasColumnName("phu_cap");

                    b.Property<int>("Thang")
                        .HasColumnType("int")
                        .HasColumnName("thang");

                    b.Property<decimal?>("Thuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12, 0)")
                        .HasDefaultValue(0m)
                        .HasColumnName("thuong");

                    b.Property<decimal?>("TongGio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(8, 2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("tong_gio");

                    b.Property<decimal?>("TongLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12, 0)")
                        .HasDefaultValue(0m)
                        .HasColumnName("tong_luong");

                    b.HasKey("MaLuong")
                        .HasName("PK__bang_luo__CC15EB614C98417D");

                    b.HasIndex("MaNv");

                    b.ToTable("bang_luong", (string)null);
                });

            modelBuilder.Entity("Billiard.DAL.Entities.ChamCong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ghi_chu");

                    b.Property<DateTime?>("GioRa")
                        .HasColumnType("datetime")
                        .HasColumnName("gio_ra");

                    b.Property<DateTime?>("GioVao")
                        .HasColumnType("datetime")
                        .HasColumnName("gio_vao");

                    b.Property<string>("HinhAnhRa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("hinh_anh_ra");

                    b.Property<string>("HinhAnhVao")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("hinh_anh_vao");

                    b.Property<int>("MaNv")
                        .HasColumnType("int")
                        .HasColumnName("ma_nv");

                    b.Property<DateOnly>("Ngay")
                        .HasColumnType("date")
                        .HasColumnName("ngay");

                    b.Property<decimal?>("SoGioLam")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("numeric(10, 6)")
                        .HasColumnName("so_gio_lam")
                        .HasComputedColumnSql("(case when [gio_ra] IS NOT NULL then CONVERT([decimal](5,2),datediff(minute,[gio_vao],[gio_ra]))/(60.0) else (0) end)", true);

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Đúng giờ")
                        .HasColumnName("trang_thai");

                    b.Property<string>("XacThucBang")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Thủ công")
                        .HasColumnName("xac_thuc_bang");

                    b.HasKey("Id")
                        .HasName("PK__cham_con__3213E83FB9920DA0");

                    b.HasIndex("MaNv");

                    b.ToTable("cham_cong", (string)null);
                });

            modelBuilder.Entity("Billiard.DAL.Entities.ChiTietHoaDon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("MaDv")
                        .HasColumnType("int")
                        .HasColumnName("ma_dv");

                    b.Property<int?>("MaHd")
                        .HasColumnType("int")
                        .HasColumnName("ma_hd");

                    b.Property<int?>("SoLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("so_luong");

                    b.Property<decimal?>("ThanhTien")
                        .HasColumnType("decimal(12, 0)")
                        .HasColumnName("thanh_tien");

                    b.HasKey("Id")
                        .HasName("PK__chi_tiet__3213E83F2C775D02");

                    b.HasIndex("MaDv");

                    b.HasIndex("MaHd");

                    b.ToTable("chi_tiet_hoa_don", null, t =>
                        {
                            t.HasTrigger("trg_CongLaiSoLuongTon_HuyMon");

                            t.HasTrigger("trg_TruSoLuongTon_BanHang");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Billiard.DAL.Entities.ChiTietPhieuNhap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DonGiaNhap")
                        .HasColumnType("decimal(10, 0)")
                        .HasColumnName("don_gia_nhap");

                    b.Property<int>("MaHang")
                        .HasColumnType("int")
                        .HasColumnName("ma_hang");

                    b.Property<int>("MaPn")
                        .HasColumnType("int")
                        .HasColumnName("ma_pn");

                    b.Property<int>("SoLuongNhap")
                        .HasColumnType("int")
                        .HasColumnName("so_luong_nhap");

                    b.Property<decimal?>("ThanhTien")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(21, 0)")
                        .HasColumnName("thanh_tien")
                        .HasComputedColumnSql("([so_luong_nhap]*[don_gia_nhap])", true);

                    b.HasKey("Id")
                        .HasName("PK__chi_tiet__3213E83F0CBC0803");

                    b.HasIndex("MaHang");

                    b.HasIndex("MaPn");

                    b.ToTable("chi_tiet_phieu_nhap", null, t =>
                        {
                            t.HasTrigger("trg_CongSoLuongTon_NhapKho");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Billiard.DAL.Entities.ChucNang", b =>
                {
                    b.Property<string>("MaCn")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ma_cn");

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("mo_ta");

                    b.Property<string>("TenCn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ten_cn");

                    b.HasKey("MaCn")
                        .HasName("PK__chuc_nan__0FE1769E06399444");

                    b.ToTable("chuc_nang", (string)null);
                });

            modelBuilder.Entity("Billiard.DAL.Entities.DatBan", b =>
                {
                    b.Property<int>("MaDat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_dat");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDat"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ghi_chu");

                    b.Property<int?>("MaBan")
                        .HasColumnType("int")
                        .HasColumnName("ma_ban");

                    b.Property<int?>("MaKh")
                        .HasColumnType("int")
                        .HasColumnName("ma_kh");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_tao")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("sdt");

                    b.Property<int?>("SoNguoi")
                        .HasColumnType("int")
                        .HasColumnName("so_nguoi");

                    b.Property<string>("TenKhach")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ten_khach");

                    b.Property<DateTime?>("ThoiGianBatDau")
                        .HasColumnType("datetime")
                        .HasColumnName("thoi_gian_bat_dau");

                    b.Property<DateTime>("ThoiGianDat")
                        .HasColumnType("datetime")
                        .HasColumnName("thoi_gian_dat");

                    b.Property<DateTime?>("ThoiGianKetThuc")
                        .HasColumnType("datetime")
                        .HasColumnName("thoi_gian_ket_thuc");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Đang chờ")
                        .HasColumnName("trang_thai");

                    b.HasKey("MaDat")
                        .HasName("PK__dat_ban__057BE11974124ACC");

                    b.HasIndex("MaBan");

                    b.HasIndex("MaKh");

                    b.HasIndex(new[] { "ThoiGianBatDau", "ThoiGianKetThuc" }, "idx_dat_ban_thoi_gian");

                    b.ToTable("dat_ban", (string)null);
                });

            modelBuilder.Entity("Billiard.DAL.Entities.DichVu", b =>
                {
                    b.Property<int>("MaDv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_dv");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDv"));

                    b.Property<string>("DonVi")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("phần")
                        .HasColumnName("don_vi");

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(10, 0)")
                        .HasColumnName("gia");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("hinh_anh");

                    b.Property<string>("Loai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Khác")
                        .HasColumnName("loai");

                    b.Property<int?>("MaHang")
                        .HasColumnType("int")
                        .HasColumnName("ma_hang");

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("mo_ta");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_tao")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("TenDv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ten_dv");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Còn hàng")
                        .HasColumnName("trang_thai");

                    b.HasKey("MaDv")
                        .HasName("PK__dich_vu__0FE14F358D88F7EC");

                    b.HasIndex("MaHang");

                    b.ToTable("dich_vu", (string)null);
                });

            modelBuilder.Entity("Billiard.DAL.Entities.GiaGioChoi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("ApDungTuNgay")
                        .HasColumnType("date")
                        .HasColumnName("ap_dung_tu_ngay");

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(10, 0)")
                        .HasColumnName("gia");

                    b.Property<TimeOnly>("GioBatDau")
                        .HasColumnType("time")
                        .HasColumnName("gio_bat_dau");

                    b.Property<TimeOnly>("GioKetThuc")
                        .HasColumnType("time")
                        .HasColumnName("gio_ket_thuc");

                    b.Property<string>("KhungGio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("khung_gio");

                    b.Property<int?>("MaLoai")
                        .HasColumnType("int")
                        .HasColumnName("ma_loai");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Đang áp dụng")
                        .HasColumnName("trang_thai");

                    b.HasKey("Id")
                        .HasName("PK__gia_gio___3213E83FA9F5FADD");

                    b.HasIndex("MaLoai");

                    b.ToTable("gia_gio_choi", (string)null);
                });

            modelBuilder.Entity("Billiard.DAL.Entities.HoaDon", b =>
                {
                    b.Property<int>("MaHd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_hd");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHd"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ghi_chu");

                    b.Property<string>("GhiChuGiamGia")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ghi_chu_giam_gia");

                    b.Property<decimal?>("GiamGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12, 0)")
                        .HasDefaultValue(0m)
                        .HasColumnName("giam_gia");

                    b.Property<int?>("MaBan")
                        .HasColumnType("int")
                        .HasColumnName("ma_ban");

                    b.Property<string>("MaGiaoDichQr")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ma_giao_dich_qr");

                    b.Property<int?>("MaKh")
                        .HasColumnType("int")
                        .HasColumnName("ma_kh");

                    b.Property<int?>("MaNv")
                        .HasColumnType("int")
                        .HasColumnName("ma_nv");

                    b.Property<string>("PhuongThucThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Tiền mặt")
                        .HasColumnName("phuong_thuc_thanh_toan");

                    b.Property<string>("QrCodeUrl")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("qr_code_url");

                    b.Property<DateTime?>("ThoiGianBatDau")
                        .HasColumnType("datetime")
                        .HasColumnName("thoi_gian_bat_dau");

                    b.Property<DateTime?>("ThoiGianKetThuc")
                        .HasColumnType("datetime")
                        .HasColumnName("thoi_gian_ket_thuc");

                    b.Property<int?>("ThoiLuongPhut")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasColumnName("thoi_luong_phut")
                        .HasComputedColumnSql("(case when [thoi_gian_ket_thuc] IS NOT NULL then datediff(minute,[thoi_gian_bat_dau],[thoi_gian_ket_thuc]) else (0) end)", true);

                    b.Property<decimal?>("TienBan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12, 0)")
                        .HasDefaultValue(0m)
                        .HasColumnName("tien_ban");

                    b.Property<decimal?>("TienDichVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12, 0)")
                        .HasDefaultValue(0m)
                        .HasColumnName("tien_dich_vu");

                    b.Property<decimal?>("TongTien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12, 0)")
                        .HasDefaultValue(0m)
                        .HasColumnName("tong_tien");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Đang chơi")
                        .HasColumnName("trang_thai");

                    b.HasKey("MaHd")
                        .HasName("PK__hoa_don__0FE16E8692E6CCF6");

                    b.HasIndex("MaBan");

                    b.HasIndex("MaKh");

                    b.HasIndex("MaNv");

                    b.ToTable("hoa_don", (string)null);
                });

            modelBuilder.Entity("Billiard.DAL.Entities.KhachHang", b =>
                {
                    b.Property<int>("MaKh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_kh");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKh"));

                    b.Property<string>("Avatar")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("avatar");

                    b.Property<int?>("DiemTichLuy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("diem_tich_luy");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("HangTv")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Đồng")
                        .HasColumnName("hang_tv");

                    b.Property<bool?>("HoatDong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("hoat_dong");

                    b.Property<DateTime?>("LanDenCuoi")
                        .HasColumnType("datetime")
                        .HasColumnName("lan_den_cuoi");

                    b.Property<string>("MatKhau")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("mat_khau");

                    b.Property<DateTime?>("NgayDangKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_dang_ky")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date")
                        .HasColumnName("ngay_sinh");

                    b.Property<string>("Sdt")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("sdt");

                    b.Property<string>("TenKh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ten_kh");

                    b.Property<decimal?>("TongChiTieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12, 0)")
                        .HasDefaultValue(0m)
                        .HasColumnName("tong_chi_tieu");

                    b.HasKey("MaKh")
                        .HasName("PK__khach_ha__0FE0B7EE42C6A3A1");

                    b.HasIndex(new[] { "Sdt" }, "UQ__khach_ha__DDDFB4839B1180CA")
                        .IsUnique()
                        .HasFilter("[sdt] IS NOT NULL");

                    b.ToTable("khach_hang", (string)null);
                });

            modelBuilder.Entity("Billiard.DAL.Entities.KhuVuc", b =>
                {
                    b.Property<int>("MaKhuVuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_khu_vuc");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhuVuc"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("mo_ta");

                    b.Property<string>("TenKhuVuc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ten_khu_vuc");

                    b.HasKey("MaKhuVuc")
                        .HasName("PK__khu_vuc__6A5E05CD906921C3");

                    b.HasIndex(new[] { "TenKhuVuc" }, "UQ__khu_vuc__5A585CB0A8D242DE")
                        .IsUnique();

                    b.ToTable("khu_vuc", (string)null);
                });

            modelBuilder.Entity("Billiard.DAL.Entities.LichSuHoatDong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChiTiet")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("chi_tiet");

                    b.Property<string>("HanhDong")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("hanh_dong");

                    b.Property<int?>("MaNv")
                        .HasColumnType("int")
                        .HasColumnName("ma_nv");

                    b.Property<DateTime?>("ThoiGian")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("thoi_gian")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK__lich_su___3213E83F9E56791C");

                    b.HasIndex("MaNv");

                    b.ToTable("lich_su_hoat_dong", (string)null);
                });

            modelBuilder.Entity("Billiard.DAL.Entities.LoaiBan", b =>
                {
                    b.Property<int>("MaLoai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_loai");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoai"));

                    b.Property<decimal>("GiaGio")
                        .HasColumnType("decimal(10, 0)")
                        .HasColumnName("gia_gio");

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("mo_ta");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ten_loai");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Đang áp dụng")
                        .HasColumnName("trang_thai");

                    b.HasKey("MaLoai")
                        .HasName("PK__loai_ban__D9476E5789660C13");

                    b.HasIndex(new[] { "TenLoai" }, "UQ__loai_ban__5FFB310CAD7B6805")
                        .IsUnique();

                    b.ToTable("loai_ban", (string)null);
                });

            modelBuilder.Entity("Billiard.DAL.Entities.MatHang", b =>
                {
                    b.Property<int>("MaHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_hang");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHang"));

                    b.Property<string>("DonVi")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("cái")
                        .HasColumnName("don_vi");

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(10, 0)")
                        .HasColumnName("gia");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("hinh_anh");

                    b.Property<string>("Loai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Khác")
                        .HasColumnName("loai");

                    b.Property<int?>("MaNccDefault")
                        .HasColumnType("int")
                        .HasColumnName("ma_ncc_default");

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("mo_ta");

                    b.Property<DateOnly?>("NgayNhapGanNhat")
                        .HasColumnType("date")
                        .HasColumnName("ngay_nhap_gan_nhat");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_tao")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("NguongCanhBao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(10)
                        .HasColumnName("nguong_canh_bao");

                    b.Property<int?>("SoLuongTon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("so_luong_ton");

                    b.Property<string>("TenHang")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ten_hang");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Còn hàng")
                        .HasColumnName("trang_thai");

                    b.HasKey("MaHang")
                        .HasName("PK__mat_hang__6DE84043F6F63F26");

                    b.HasIndex("MaNccDefault");

                    b.ToTable("mat_hang", (string)null);
                });

            modelBuilder.Entity("Billiard.DAL.Entities.NhaCungCap", b =>
                {
                    b.Property<int>("MaNcc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_ncc");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNcc"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("dia_chi");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Sdt")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("sdt");

                    b.Property<string>("TenNcc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ten_ncc");

                    b.HasKey("MaNcc")
                        .HasName("PK__nha_cung__04FFEEB97AD2B3ED");

                    b.ToTable("nha_cung_cap", (string)null);
                });

            modelBuilder.Entity("Billiard.DAL.Entities.NhanVien", b =>
                {
                    b.Property<int>("MaNv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_nv");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNv"));

                    b.Property<string>("CaMacDinh")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("Sáng")
                        .HasColumnName("ca_mac_dinh");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("FaceidAnh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("faceid_anh");

                    b.Property<string>("FaceidHash")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("faceid_hash");

                    b.Property<decimal?>("LuongCoBan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12, 0)")
                        .HasDefaultValue(0m)
                        .HasColumnName("luong_co_ban");

                    b.Property<int>("MaNhom")
                        .HasColumnType("int")
                        .HasColumnName("ma_nhom");

                    b.Property<string>("MaVanTay")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ma_van_tay");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("mat_khau");

                    b.Property<decimal?>("PhuCap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12, 0)")
                        .HasDefaultValue(0m)
                        .HasColumnName("phu_cap");

                    b.Property<string>("Sdt")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("sdt");

                    b.Property<string>("TenNv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ten_nv");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Đang làm")
                        .HasColumnName("trang_thai");

                    b.HasKey("MaNv")
                        .HasName("PK__nhan_vie__0FE15F7CD9B29355");

                    b.HasIndex("MaNhom");

                    b.HasIndex(new[] { "MaVanTay" }, "UQ__nhan_vie__C17D2329E67CBEE1")
                        .IsUnique()
                        .HasFilter("[ma_van_tay] IS NOT NULL");

                    b.HasIndex(new[] { "FaceidHash" }, "UQ__nhan_vie__E37BF412AB415224")
                        .IsUnique()
                        .HasFilter("[faceid_hash] IS NOT NULL");

                    b.ToTable("nhan_vien", (string)null);
                });

            modelBuilder.Entity("Billiard.DAL.Entities.NhomQuyen", b =>
                {
                    b.Property<int>("MaNhom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_nhom");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhom"));

                    b.Property<string>("TenNhom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ten_nhom");

                    b.HasKey("MaNhom")
                        .HasName("PK__nhom_quy__9B8FD98CCE19E15A");

                    b.HasIndex(new[] { "TenNhom" }, "UQ__nhom_quy__CA147C69D99B9308")
                        .IsUnique();

                    b.ToTable("nhom_quyen", (string)null);
                });

            modelBuilder.Entity("Billiard.DAL.Entities.PhieuNhap", b =>
                {
                    b.Property<int>("MaPn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_pn");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPn"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ghi_chu");

                    b.Property<int>("MaNcc")
                        .HasColumnType("int")
                        .HasColumnName("ma_ncc");

                    b.Property<int>("MaNv")
                        .HasColumnType("int")
                        .HasColumnName("ma_nv");

                    b.Property<DateTime?>("NgayNhap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_nhap")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("TongTien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12, 0)")
                        .HasDefaultValue(0m)
                        .HasColumnName("tong_tien");

                    b.HasKey("MaPn")
                        .HasName("PK__phieu_nh__0FE0AFB6136FC471");

                    b.HasIndex("MaNcc");

                    b.HasIndex("MaNv");

                    b.ToTable("phieu_nhap", (string)null);
                });

            modelBuilder.Entity("Billiard.DAL.Entities.SoQuy", b =>
                {
                    b.Property<int>("MaPhieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_phieu");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieu"));

                    b.Property<string>("LoaiPhieu")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("loai_phieu");

                    b.Property<string>("LyDo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("ly_do");

                    b.Property<int?>("MaHdLienQuan")
                        .HasColumnType("int")
                        .HasColumnName("ma_hd_lien_quan");

                    b.Property<int>("MaNv")
                        .HasColumnType("int")
                        .HasColumnName("ma_nv");

                    b.Property<DateTime?>("NgayLap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_lap")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(12, 0)")
                        .HasColumnName("so_tien");

                    b.HasKey("MaPhieu")
                        .HasName("PK__so_quy__11D0F07A4814454C");

                    b.HasIndex("MaHdLienQuan");

                    b.HasIndex("MaNv");

                    b.ToTable("so_quy", (string)null);
                });

            modelBuilder.Entity("Billiard.DAL.Entities.VBaoCaoVietQr", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int?>("MaBan")
                        .HasColumnType("int")
                        .HasColumnName("ma_ban");

                    b.Property<string>("MaGiaoDich")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ma_giao_dich");

                    b.Property<string>("MaGiaoDichNganHang")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ma_giao_dich_ngan_hang");

                    b.Property<int>("MaHd")
                        .HasColumnType("int")
                        .HasColumnName("ma_hd");

                    b.Property<DateTime?>("NgayHetHan")
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_het_han");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_tao");

                    b.Property<string>("NoiDung")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("noi_dung");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(12, 0)")
                        .HasColumnName("so_tien");

                    b.Property<string>("TenBan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ten_ban");

                    b.Property<string>("TenKh")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ten_kh");

                    b.Property<DateTime?>("ThoiGianThanhToan")
                        .HasColumnType("datetime")
                        .HasColumnName("thoi_gian_thanh_toan");

                    b.Property<int?>("ThoiGianThanhToanGiay")
                        .HasColumnType("int")
                        .HasColumnName("thoi_gian_thanh_toan_giay");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("trang_thai");

                    b.ToTable((string)null);

                    b.ToView("v_BaoCaoVietQR", (string)null);
                });

            modelBuilder.Entity("Billiard.DAL.Entities.VietqrConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("account_name");

                    b.Property<string>("AccountNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("account_no");

                    b.Property<string>("ApiKey")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("api_key");

                    b.Property<string>("ApiUrl")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("api_url");

                    b.Property<string>("BankId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("bank_id");

                    b.Property<string>("ClientId")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("client_id");

                    b.Property<bool?>("LaMacDinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("la_mac_dinh");

                    b.Property<DateTime?>("NgayCapNhat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_cap_nhat")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_tao")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Template")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("compact")
                        .HasColumnName("template");

                    b.Property<string>("TenCauHinh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ten_cau_hinh");

                    b.Property<bool?>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("trang_thai");

                    b.Property<string>("WebhookSecret")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("webhook_secret");

                    b.Property<string>("WebhookUrl")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("webhook_url");

                    b.HasKey("Id")
                        .HasName("PK__vietqr_c__3213E83F5C8B373C");

                    b.ToTable("vietqr_config", (string)null);
                });

            modelBuilder.Entity("Billiard.DAL.Entities.VietqrGiaoDich", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("account_name");

                    b.Property<string>("AccountNo")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("account_no");

                    b.Property<string>("BankId")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("bank_id");

                    b.Property<string>("MaGiaoDich")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ma_giao_dich");

                    b.Property<string>("MaGiaoDichNganHang")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ma_giao_dich_ngan_hang");

                    b.Property<int>("MaHd")
                        .HasColumnType("int")
                        .HasColumnName("ma_hd");

                    b.Property<DateTime?>("NgayHetHan")
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_het_han");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_tao")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NoiDung")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("noi_dung");

                    b.Property<string>("NoiDungThucTe")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("noi_dung_thuc_te");

                    b.Property<string>("QrCodeBase64")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("qr_code_base64");

                    b.Property<string>("QrCodeUrl")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("qr_code_url");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(12, 0)")
                        .HasColumnName("so_tien");

                    b.Property<DateTime?>("ThoiGianThanhToan")
                        .HasColumnType("datetime")
                        .HasColumnName("thoi_gian_thanh_toan");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Chờ thanh toán")
                        .HasColumnName("trang_thai");

                    b.HasKey("Id")
                        .HasName("PK__vietqr_g__3213E83FF917D349");

                    b.HasIndex(new[] { "MaGiaoDich" }, "UQ__vietqr_g__FB80ED332688027D")
                        .IsUnique();

                    b.HasIndex(new[] { "MaGiaoDich" }, "idx_vietqr_giao_dich_ma_giao_dich");

                    b.HasIndex(new[] { "MaHd" }, "idx_vietqr_giao_dich_ma_hd");

                    b.HasIndex(new[] { "TrangThai" }, "idx_vietqr_giao_dich_trang_thai");

                    b.ToTable("vietqr_giao_dich", (string)null);
                });

            modelBuilder.Entity("Billiard.DAL.Entities.VietqrWebhookLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Headers")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("headers");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ip_address");

                    b.Property<string>("MaGiaoDich")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ma_giao_dich");

                    b.Property<string>("Payload")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ThoiGianNhan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("thoi_gian_nhan")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("ThongBaoLoi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("thong_bao_loi");

                    b.Property<bool?>("XuLyThanhCong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("xu_ly_thanh_cong");

                    b.HasKey("Id")
                        .HasName("PK__vietqr_w__3213E83FD9C75BB4");

                    b.ToTable("vietqr_webhook_log", (string)null);
                });

            modelBuilder.Entity("PhanQuyen", b =>
                {
                    b.Property<int>("MaNhom")
                        .HasColumnType("int")
                        .HasColumnName("ma_nhom");

                    b.Property<string>("MaCn")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ma_cn");

                    b.HasKey("MaNhom", "MaCn")
                        .HasName("PK__phan_quy__6B71CEE5E61FCB0B");

                    b.HasIndex("MaCn");

                    b.ToTable("phan_quyen", (string)null);
                });

            modelBuilder.Entity("Billiard.DAL.Entities.BanBium", b =>
                {
                    b.HasOne("Billiard.DAL.Entities.KhachHang", "MaKhNavigation")
                        .WithMany("BanBia")
                        .HasForeignKey("MaKh")
                        .HasConstraintName("FK__ban_bia__ma_kh__4F7CD00D");

                    b.HasOne("Billiard.DAL.Entities.KhuVuc", "MaKhuVucNavigation")
                        .WithMany("BanBia")
                        .HasForeignKey("MaKhuVuc")
                        .IsRequired()
                        .HasConstraintName("FK__ban_bia__ma_khu___5070F446");

                    b.HasOne("Billiard.DAL.Entities.LoaiBan", "MaLoaiNavigation")
                        .WithMany("BanBia")
                        .HasForeignKey("MaLoai")
                        .IsRequired()
                        .HasConstraintName("FK__ban_bia__ma_loai__4E88ABD4");

                    b.Navigation("MaKhNavigation");

                    b.Navigation("MaKhuVucNavigation");

                    b.Navigation("MaLoaiNavigation");
                });

            modelBuilder.Entity("Billiard.DAL.Entities.BangLuong", b =>
                {
                    b.HasOne("Billiard.DAL.Entities.NhanVien", "MaNvNavigation")
                        .WithMany("BangLuongs")
                        .HasForeignKey("MaNv")
                        .IsRequired()
                        .HasConstraintName("FK__bang_luon__ma_nv__18EBB532");

                    b.Navigation("MaNvNavigation");
                });

            modelBuilder.Entity("Billiard.DAL.Entities.ChamCong", b =>
                {
                    b.HasOne("Billiard.DAL.Entities.NhanVien", "MaNvNavigation")
                        .WithMany("ChamCongs")
                        .HasForeignKey("MaNv")
                        .IsRequired()
                        .HasConstraintName("FK__cham_cong__ma_nv__0F624AF8");

                    b.Navigation("MaNvNavigation");
                });

            modelBuilder.Entity("Billiard.DAL.Entities.ChiTietHoaDon", b =>
                {
                    b.HasOne("Billiard.DAL.Entities.DichVu", "MaDvNavigation")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("MaDv")
                        .HasConstraintName("FK__chi_tiet___ma_dv__2A164134");

                    b.HasOne("Billiard.DAL.Entities.HoaDon", "MaHdNavigation")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("MaHd")
                        .HasConstraintName("FK__chi_tiet___ma_hd__29221CFB");

                    b.Navigation("MaDvNavigation");

                    b.Navigation("MaHdNavigation");
                });

            modelBuilder.Entity("Billiard.DAL.Entities.ChiTietPhieuNhap", b =>
                {
                    b.HasOne("Billiard.DAL.Entities.MatHang", "MaHangNavigation")
                        .WithMany("ChiTietPhieuNhaps")
                        .HasForeignKey("MaHang")
                        .IsRequired()
                        .HasConstraintName("FK__chi_tiet___ma_ha__7A672E12");

                    b.HasOne("Billiard.DAL.Entities.PhieuNhap", "MaPnNavigation")
                        .WithMany("ChiTietPhieuNhaps")
                        .HasForeignKey("MaPn")
                        .IsRequired()
                        .HasConstraintName("FK__chi_tiet___ma_pn__797309D9");

                    b.Navigation("MaHangNavigation");

                    b.Navigation("MaPnNavigation");
                });

            modelBuilder.Entity("Billiard.DAL.Entities.DatBan", b =>
                {
                    b.HasOne("Billiard.DAL.Entities.BanBium", "MaBanNavigation")
                        .WithMany("DatBans")
                        .HasForeignKey("MaBan")
                        .HasConstraintName("FK__dat_ban__ma_ban__5629CD9C");

                    b.HasOne("Billiard.DAL.Entities.KhachHang", "MaKhNavigation")
                        .WithMany("DatBans")
                        .HasForeignKey("MaKh")
                        .HasConstraintName("FK__dat_ban__ma_kh__571DF1D5");

                    b.Navigation("MaBanNavigation");

                    b.Navigation("MaKhNavigation");
                });

            modelBuilder.Entity("Billiard.DAL.Entities.DichVu", b =>
                {
                    b.HasOne("Billiard.DAL.Entities.MatHang", "MaHangNavigation")
                        .WithMany("DichVus")
                        .HasForeignKey("MaHang")
                        .HasConstraintName("FK__dich_vu__ma_hang__02FC7413");

                    b.Navigation("MaHangNavigation");
                });

            modelBuilder.Entity("Billiard.DAL.Entities.GiaGioChoi", b =>
                {
                    b.HasOne("Billiard.DAL.Entities.LoaiBan", "MaLoaiNavigation")
                        .WithMany("GiaGioChois")
                        .HasForeignKey("MaLoai")
                        .HasConstraintName("FK__gia_gio_c__ma_lo__3493CFA7");

                    b.Navigation("MaLoaiNavigation");
                });

            modelBuilder.Entity("Billiard.DAL.Entities.HoaDon", b =>
                {
                    b.HasOne("Billiard.DAL.Entities.BanBium", "MaBanNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaBan")
                        .HasConstraintName("FK__hoa_don__ma_ban__236943A5");

                    b.HasOne("Billiard.DAL.Entities.KhachHang", "MaKhNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaKh")
                        .HasConstraintName("FK__hoa_don__ma_kh__245D67DE");

                    b.HasOne("Billiard.DAL.Entities.NhanVien", "MaNvNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaNv")
                        .HasConstraintName("FK__hoa_don__ma_nv__25518C17");

                    b.Navigation("MaBanNavigation");

                    b.Navigation("MaKhNavigation");

                    b.Navigation("MaNvNavigation");
                });

            modelBuilder.Entity("Billiard.DAL.Entities.LichSuHoatDong", b =>
                {
                    b.HasOne("Billiard.DAL.Entities.NhanVien", "MaNvNavigation")
                        .WithMany("LichSuHoatDongs")
                        .HasForeignKey("MaNv")
                        .HasConstraintName("FK__lich_su_h__ma_nv__3864608B");

                    b.Navigation("MaNvNavigation");
                });

            modelBuilder.Entity("Billiard.DAL.Entities.MatHang", b =>
                {
                    b.HasOne("Billiard.DAL.Entities.NhaCungCap", "MaNccDefaultNavigation")
                        .WithMany("MatHangs")
                        .HasForeignKey("MaNccDefault")
                        .HasConstraintName("FK__mat_hang__ma_ncc__6383C8BA");

                    b.Navigation("MaNccDefaultNavigation");
                });

            modelBuilder.Entity("Billiard.DAL.Entities.NhanVien", b =>
                {
                    b.HasOne("Billiard.DAL.Entities.NhomQuyen", "MaNhomNavigation")
                        .WithMany("NhanViens")
                        .HasForeignKey("MaNhom")
                        .IsRequired()
                        .HasConstraintName("FK__nhan_vien__ma_nh__70DDC3D8");

                    b.Navigation("MaNhomNavigation");
                });

            modelBuilder.Entity("Billiard.DAL.Entities.PhieuNhap", b =>
                {
                    b.HasOne("Billiard.DAL.Entities.NhaCungCap", "MaNccNavigation")
                        .WithMany("PhieuNhaps")
                        .HasForeignKey("MaNcc")
                        .IsRequired()
                        .HasConstraintName("FK__phieu_nha__ma_nc__76969D2E");

                    b.HasOne("Billiard.DAL.Entities.NhanVien", "MaNvNavigation")
                        .WithMany("PhieuNhaps")
                        .HasForeignKey("MaNv")
                        .IsRequired()
                        .HasConstraintName("FK__phieu_nha__ma_nv__75A278F5");

                    b.Navigation("MaNccNavigation");

                    b.Navigation("MaNvNavigation");
                });

            modelBuilder.Entity("Billiard.DAL.Entities.SoQuy", b =>
                {
                    b.HasOne("Billiard.DAL.Entities.HoaDon", "MaHdLienQuanNavigation")
                        .WithMany("SoQuies")
                        .HasForeignKey("MaHdLienQuan")
                        .HasConstraintName("FK__so_quy__ma_hd_li__2FCF1A8A");

                    b.HasOne("Billiard.DAL.Entities.NhanVien", "MaNvNavigation")
                        .WithMany("SoQuies")
                        .HasForeignKey("MaNv")
                        .IsRequired()
                        .HasConstraintName("FK__so_quy__ma_nv__2EDAF651");

                    b.Navigation("MaHdLienQuanNavigation");

                    b.Navigation("MaNvNavigation");
                });

            modelBuilder.Entity("Billiard.DAL.Entities.VietqrGiaoDich", b =>
                {
                    b.HasOne("Billiard.DAL.Entities.HoaDon", "MaHdNavigation")
                        .WithMany("VietqrGiaoDiches")
                        .HasForeignKey("MaHd")
                        .IsRequired()
                        .HasConstraintName("FK__vietqr_gi__ma_hd__3F115E1A");

                    b.Navigation("MaHdNavigation");
                });

            modelBuilder.Entity("PhanQuyen", b =>
                {
                    b.HasOne("Billiard.DAL.Entities.ChucNang", null)
                        .WithMany()
                        .HasForeignKey("MaCn")
                        .IsRequired()
                        .HasConstraintName("FK__phan_quye__ma_cn__08B54D69");

                    b.HasOne("Billiard.DAL.Entities.NhomQuyen", null)
                        .WithMany()
                        .HasForeignKey("MaNhom")
                        .IsRequired()
                        .HasConstraintName("FK__phan_quye__ma_nh__07C12930");
                });

            modelBuilder.Entity("Billiard.DAL.Entities.BanBium", b =>
                {
                    b.Navigation("DatBans");

                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("Billiard.DAL.Entities.DichVu", b =>
                {
                    b.Navigation("ChiTietHoaDons");
                });

            modelBuilder.Entity("Billiard.DAL.Entities.HoaDon", b =>
                {
                    b.Navigation("ChiTietHoaDons");

                    b.Navigation("SoQuies");

                    b.Navigation("VietqrGiaoDiches");
                });

            modelBuilder.Entity("Billiard.DAL.Entities.KhachHang", b =>
                {
                    b.Navigation("BanBia");

                    b.Navigation("DatBans");

                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("Billiard.DAL.Entities.KhuVuc", b =>
                {
                    b.Navigation("BanBia");
                });

            modelBuilder.Entity("Billiard.DAL.Entities.LoaiBan", b =>
                {
                    b.Navigation("BanBia");

                    b.Navigation("GiaGioChois");
                });

            modelBuilder.Entity("Billiard.DAL.Entities.MatHang", b =>
                {
                    b.Navigation("ChiTietPhieuNhaps");

                    b.Navigation("DichVus");
                });

            modelBuilder.Entity("Billiard.DAL.Entities.NhaCungCap", b =>
                {
                    b.Navigation("MatHangs");

                    b.Navigation("PhieuNhaps");
                });

            modelBuilder.Entity("Billiard.DAL.Entities.NhanVien", b =>
                {
                    b.Navigation("BangLuongs");

                    b.Navigation("ChamCongs");

                    b.Navigation("HoaDons");

                    b.Navigation("LichSuHoatDongs");

                    b.Navigation("PhieuNhaps");

                    b.Navigation("SoQuies");
                });

            modelBuilder.Entity("Billiard.DAL.Entities.NhomQuyen", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("Billiard.DAL.Entities.PhieuNhap", b =>
                {
                    b.Navigation("ChiTietPhieuNhaps");
                });
#pragma warning restore 612, 618
        }
    }
}
