<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Forms\Resources\img\ban_maxim.jpg" />
    <None Remove="Images\Banner\img2.png" />
    <None Remove="Images\Banner\img3.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Forms\Resources\img\ban_maxim.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\Banner\img3.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Content Include="Images\Banner\banner1.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\Banner\img2.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="API_Integration\" />
    <Folder Include="Forms\Resources\Images\Services\" />
    <Folder Include="Forms\Resources\Images\Tables\" />
    <Folder Include="viewModels\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="EPPlus" Version="8.4.1" />
    <PackageReference Include="HIC.System.Windows.Forms.DataVisualization" Version="1.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.22" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Billiard.API\Billiard.API.csproj" />
    <ProjectReference Include="..\Billiard.BLL\Billiard.BLL.csproj" />
    <ProjectReference Include="..\Billiard.DAL\Billiard.DAL.csproj" />
    <ProjectReference Include="..\Billiards.Shared\Billiard.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="Forms\Resources\img\avatar_khach_hang\09363b77-bd18-4898-9d89-d51f3e623773.JPG">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Forms\Resources\img\avatar_khach_hang\779b894b-d627-4b9c-bbdd-655c63f00fec.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Forms\Resources\img\avatar_khach_hang\8108069d-ca71-4e10-b1b3-0927c993fcf3.JPG">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Forms\Resources\img\avatar_khach_hang\a07bec70-3725-46f3-8a63-06741cd5ccae.JPG">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Forms\Resources\img\avatar_khach_hang\bb756ff6-07a2-41f7-98b2-bd008f706807.JPG">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Forms\Resources\img\avatar_khach_hang\user.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>